#!/usr/bin/env python3

import json
import os


build_number  = os.environ['BUILD_NUMBER']
build_id      = os.environ['BUILD_ID']
build_url     = os.environ['BUILD_URL']
job_name      = os.environ['JOB_NAME']
job_base_name = os.environ['JOB_BASE_NAME']
git_commit    = os.environ['GIT_COMMIT']

print("build number: ", format(build_number))
print("build id: ", format(build_id))
print("job name: ", format(job_name))
print("job base name: ", format(job_base_name))
print("build url: ", format(build_url))
print("git commit: ", format(git_commit))

